# Site settings
title: Vita.io
email: info@vita.io
description: Homepage of Vita.IO
baseurl: "/" #"/vita-io" # the subpath of your site, e.g. /blog/
url: "http://vita.io" # the base hostname & protocol for your site
vacancyEmail: apply@vita.io
safe: true
lsi: false

contact:
  address: Heer Bokelweg 155
  zipcode: 3032 AD
  city: Rotterdam
  country: The Netherlands
  email: hello@vita.io
  phone: 012-3456789
  twitter: VitaAnalytics

collections:
  - vacancies

markdown: kramdown
exclude:
  - assets/
  - bower_components/
  - gulp/
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules/
  - package.json
  - README.md
  - vita.io.sublime-project
  - vita.io.sublime-workspace

source: ./